version: '3'

services:
  sandbox-app:
    build: ..
    env_file:
      - sandbox-app.env
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_REDIS_HOST=redis
      - JAVA_OPTS=--enable-preview
    depends_on:
      - rabbitmq
      - redis
    ports:
      - 8080:8080
    volumes:
      - maven_repo:/root/.m2

  rabbitmq:
    build: ./rabbitmq
    ports:
      - 15672:15672

  redis:
    image: "redis:5.0.8-alpine"
    command: redis-server --requirepass "1VBnoRGtFG1GuE9/xd7hCfav4CJ40+ZCHA==" --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  maven_repo:
  redis_data: