version: '3'

services:
  sandbox-app:
    build: ..
    env_file:
      - sandbox-app.env
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_REDIS_HOST=redis
    depends_on:
      - rabbitmq
      - redis
    ports:
      - 8080:8080

  rabbitmq:
    build: ./rabbitmq
    ports:
      - 15672:15672

  redis:
    image: "redis:5.0.5-alpine"
    command: redis-server --requirepass "1VBnoRGtFG1GuE9/xd7hCfav4CJ40+ZCHA=="